version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: local-test-mongodb
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/mydatabase
      - APP_URL=${APP_URL}
      - GITHUB_OAUTH_ID=${GITHUB_OAUTH_ID}
      - GITHUB_OAUTH_SECRET=${GITHUB_OAUTH_SECRET}
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
